# Generated by Django 5.0.4 on 2024-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_exp',
            field=models.FloatField(),
        ),
    ]
